apiVersion: cis.f5.com/v1
kind: TLSProfile
metadata: 
  labels: 
    f5cr: "true"
  name: passthrough-tls-cafe
  namespace: nginx-ingress
spec: 
  hosts: 
    - cafe.example.com
  tls:
    termination: passthrough