apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: f5-cafe-443
  namespace: nginx-ingress
  labels:
    f5cr: "true"
spec:
  host: cafe.example.com
  virtualServerAddress: "10.192.75.111"
  virtualServerHTTPSPort: 443
  snat: auto
  pools:
  - path: /
    service: nginx-ingress
    servicePort: 443