apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: f5-cafe-443
  namespace: nginx-ingress
  labels:
    f5cr: "true"
spec:
  host: cafe.example.com
  virtualServerAddress: "10.192.75.111"
  virtualServerHTTPSPort: 443
  tlsProfileName: passthrough-tls-cafe
  snat: auto
  iRules:
    - /Common/Proxy_Protocol_iRule
  pools:
  - path: /
    service: nginx-ingress
    servicePort: 443
    monitor:
      interval: 20
      recv: ""
      send: /
      timeout: 10
      type: https