apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: f5-cafe-443
  namespace: nginx-ingress
  labels:
    f5cr: "true"
spec:
  host: cafe.example.com
  virtualServerAddress: "10.192.75.111"
  virtualServerHTTPSPort: 443
  tlsProfileName: passthrough-tls-cafe
  snat: auto
  pools:
  - monitor:
      interval: 10
      recv: ""
      send: 'GET /coffee HTTP/1.1\r\nHost: cafe.example.com\r\nConnection: Close\r\n\r\n'
      timeout: 10
      type: https
    path: /
    service: nginx-ingress
    servicePort: 443